### ISSUE TITLE
Bug when trying to fetch from github ?

### ISSUE THREAD

**Issue by mathieunicolas** [unjs/unstorage#242]
### Environment

Nuxt 3.5.2 and Docus 1.12.0, running for dev on up-to-date macOS.

### Reproduction

https://stackblitz.com/edit/github-fiye19?file=nuxt.config.ts

### Describe the bug

I want to fetch MD files from a github repo, and there's an error. 
Quick search don't give me any clue on what's happening.

### Additional context

There's more details on the stackblitz error, the logs below are from my macOS machine.

### Logs

```sh
[nuxt] [request error] [unhandled] [500] Cannot convert undefined or null to object                                                                             1:44:19 AM
  at Function.keys (<anonymous>)  
  at getKeys (./node_modules/unstorage/drivers/github.mjs:38:21)  
  at async Object.getKeys (./node_modules/unstorage/dist/index.mjs:224:25)  
  at async getContentsIds (./.nuxt/dev/index.mjs:4686:12)  
  at async getContentsList (./.nuxt/dev/index.mjs:4710:16)  
  at async getContentIndex (./.nuxt/dev/index.mjs:4639:18)  
  at async getIndexedContentsList (./.nuxt/dev/index.mjs:4657:19)  
  at async ./.nuxt/dev/index.mjs:2154:18  
  at async ./.nuxt/dev/index.mjs:4893:21  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1255:19)
```

**Comment by Hebilicious** [comment]
I'm unable to reproduce your issue with `unstorage`. I'm able to read your repository with the unstorage github driver without any issue. 

This is probably an issue with nuxt-content or docus. Could you please open an issue there ?
