### ISSUE TITLE
[fs] `getKeys`  does not works for mounts within `node_modules`

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#477]
### Environment

-

### Reproduction

Mount a driver within `node_modules` path.

### Describe the bug

https://github.com/unjs/unstorage/blob/0e2ea339a65995c9ef1e2130a293f0928a2c9de1/src/drivers/fs.ts#L32

**Comment by oritwoen** [comment]
"Today bug". Yesterday my script working perfectly fine.

Today, with this:

```js
const storage = createStorage({
	driver: fsDriver({ base: "./" }),
});

const packages = await storage.getKeys();
```

I got:
```sh
file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:39
    entries.map(async (entry) => {
            ^

TypeError: entries.map is not a function
    at readdirRecursive (file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:39:13)
    at async file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:42:26
    at async Promise.all (index 2)
    at async readdirRecursive (file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:38:3)
    at async file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:42:26
    at async Promise.all (index 43)
    at async readdirRecursive (file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/drivers/utils/node-fs.mjs:38:3)
    at async Object.getKeys (file:///home/oritwoen/Projekty/Archex/node_modules/.pnpm/unstorage@1.11.1/node_modules/unstorage/dist/index.mjs:314:25)
    at async file:///home/oritwoen/Projekty/Archex/build.mjs:10:18
```

**Comment by pi0** [comment]
@oritwoen i'm not sure it is the same issue... And also [this stackblitz works](https://stackblitz.com/edit/stackblitz-starters-fs7uml?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=package.json,index.mjs&title=node.new%20Starter) with latest version.

If you could make a reproduction, please open a new issue 🙏🏼
